# Generated by Django 4.2.7 on 2025-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_userprofile_current_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="rank_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
